global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "dangquangepu1701@gmail.com"
  smtp_auth_username: "dangquangepu1701@gmail.com"
  smtp_auth_identity: "dangquangepu1701@gmail.com"
  smtp_auth_password: "quang12345"
  resolve_timeout: 3m

templates:
  - "/etc/alertmanager/template/*.tmpl"

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: email

  routes:
    - matchers:
        - notify="email"
      receiver: email

    - matchers:
        - notify="telegram"
      receiver: telegram

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname]

receivers:
  - name: "email"
    email_configs:
      - to: "nnhuyenmyepu1701@gmail.com"
        send_resolved: true

  - name: "telegram"
    webhook_configs:
      - url: "http://192.168.5.42:9087/alert/-879785550"
        send_resolved: true
